server:
  port: 8081

spring:


  datasource:
    url: jdbc:mysql://localhost:3306/poszkoleapp?useSSL=false&serverTimezone=Europe/Warsaw
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: tomekwaz11


  jpa:
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: false
      show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

